// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAG2-DqPPiU5F9H9mxwoeotoFQEwPSTIQk',
    appId: '1:634559403892:web:5841324703cc9546b27e21',
    messagingSenderId: '634559403892',
    projectId: 'biyemek-5e6ed',
    authDomain: 'biyemek-5e6ed.firebaseapp.com',
    storageBucket: 'biyemek-5e6ed.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWxXBoudmXPTqNlmv48dCo9Iv_OmbFI2I',
    appId: '1:634559403892:android:7c273d524da6f5b9b27e21',
    messagingSenderId: '634559403892',
    projectId: 'biyemek-5e6ed',
    storageBucket: 'biyemek-5e6ed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8dDq6-joWdxNno48AdLacFBGMsLck8z0',
    appId: '1:634559403892:ios:f78791117950d4fcb27e21',
    messagingSenderId: '634559403892',
    projectId: 'biyemek-5e6ed',
    storageBucket: 'biyemek-5e6ed.appspot.com',
    androidClientId: '634559403892-t2snjhq352pppfc5a313mfqigh8n24ha.apps.googleusercontent.com',
    iosClientId: '634559403892-6t033jv3ltk0m0hi0hctb69sbuaaq0kn.apps.googleusercontent.com',
    iosBundleId: 'com.example.biyemek',
  );
}
